# syntax=docker/dockerfile:1

FROM node:22-bookworm-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

RUN corepack enable \
    && corepack prepare pnpm@9.12.0 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY db ./db
COPY tooling ./tooling
COPY drizzle.config.ts ./

ENV NODE_ENV=production

CMD ["pnpm", "db:migrate"]
